import { Hono } from 'hono';
import type { Context } from 'hono';
import { all, first, updateRow, now } from '../db';
import { fmtDate, todayStr } from '../dates';
import { activeUsers, flash } from '../auth';
import { page, Card, PageHeader, EmptyState, StatCard, taskBadge, isTaskOverdue, Icon, IconAction, IconModalBtn, Modal, ModalButtons, Field } from '../ui';
import { isAdmin, ROLE_LABELS, TASK_TYPE_LABELS, type App, type Task, type TaskStatus, type TaskType, type Visit } from '../types';

const routes = new Hono<App>();

type TaskRow = Task & { plan_number: string; vendor_name: string; assigned_to_name: string; vendor_coordinator_id: string };

const FILTERS: { value: string; label: string }[] = [
  { value: 'open', label: 'All open' },
  { value: 'pending', label: 'Pending' },
  { value: 'in_progress', label: 'In progress' },
  { value: 'overdue', label: 'Overdue' },
  { value: 'completed', label: 'Completed' },
  { value: 'cancelled', label: 'Cancelled' },
  { value: 'all', label: 'Everything' },
];

routes.get('/', async (c) => {
  const db = c.env.DB;
  const user = c.get('user');
  const filter = c.req.query('status') ?? 'open';
  const showAll = c.req.query('all') === '1' && isAdmin(user);
  const today = todayStr();

  const tasks = await all<TaskRow>(
    db,
    `SELECT t.*, COALESCE(r.plan_number, 'Ad-hoc ' || v.notification_number, 'Ad-hoc') AS plan_number, ve.name AS vendor_name, u.full_name AS assigned_to_name, v.vendor_coordinator_id
     FROM tasks t
     JOIN visits v ON v.id = t.visit_id
     LEFT JOIN routines r ON r.id = v.routine_id
     JOIN vendors ve ON ve.id = COALESCE(r.vendor_id, v.vendor_id)
     JOIN users u ON u.id = t.assigned_to_id
     ${showAll ? '' : 'WHERE t.assigned_to_id = ?'}
     ORDER BY t.due_date`,
    ...(showAll ? [] : [user.id])
  );

  const overdue = (t: TaskRow) => isTaskOverdue(t.status, t.due_date);
  const counts = {
    pending: tasks.filter((t) => t.status === 'pending' && !overdue(t)).length,
    in_progress: tasks.filter((t) => t.status === 'in_progress' && !overdue(t)).length,
    overdue: tasks.filter(overdue).length,
    completed: tasks.filter((t) => t.status === 'completed').length,
  };
  const visible = tasks.filter((t) => {
    if (filter === 'all') return true;
    if (filter === 'open') return ['pending', 'in_progress', 'overdue'].includes(t.status);
    if (filter === 'overdue') return overdue(t);
    return t.status === filter;
  });
  const query = (f: string) => `/tasks?status=${f}${showAll ? '&all=1' : ''}`;
  // Admins and the visit's coordinator can hand an open task to someone else
  // (holidays, sickness) without reassigning the whole team.
  const canReassign = (t: TaskRow) =>
    ['pending', 'in_progress', 'overdue'].includes(t.status) && (isAdmin(user) || user.id === t.vendor_coordinator_id);
  const reassignable = visible.filter(canReassign);
  const users = reassignable.length > 0 ? await activeUsers(db) : [];

  return page(c, showAll ? 'All Tasks' : 'My Tasks', (
    <>
      <PageHeader title={showAll ? 'All Tasks' : 'My Tasks'} sub="Workflow to-dos with deadlines, generated by the visit lifecycle" />

      <div class="stats">
        <StatCard label="Pending" value={counts.pending} href={query('pending')} icon="clock" tone="amber" />
        <StatCard label="In Progress" value={counts.in_progress} href={query('in_progress')} icon="clock" tone="blue" />
        <StatCard label="Overdue" value={counts.overdue} href={query('overdue')} icon="alert" tone="red" />
        <StatCard label="Completed" value={counts.completed} href={query('completed')} icon="check" tone="green" />
      </div>

      <Card pad={false}>
        <form class="filterbar" method="get" action="/tasks">
          <select name="status" data-autosubmit aria-label="Filter tasks">
            {FILTERS.map((f) => <option value={f.value} selected={filter === f.value}>{f.label}</option>)}
          </select>
          {isAdmin(user) && (
            <label class="check" style="margin:0">
              <input type="checkbox" name="all" value="1" checked={showAll} data-autosubmit /> Show all users
            </label>
          )}
          <span class="muted">{visible.length} task{visible.length === 1 ? '' : 's'}</span>
        </form>
        {visible.length === 0 ? (
          <EmptyState title="No tasks found" hint={filter !== 'all' ? 'Try a different filter.' : 'Tasks appear here as visits move through their workflow.'} />
        ) : (
          <div class="tbl-wrap">
            <table class="tbl">
              <thead>
                <tr>
                  <th>Task</th><th>Plan / Vendor</th>{showAll && <th>Assigned To</th>}<th>Due</th><th>Status</th><th class="actions">Actions</th>
                </tr>
              </thead>
              <tbody>
                {visible.map((t) => {
                  const mine = t.assigned_to_id === user.id || isAdmin(user);
                  const open = ['pending', 'in_progress', 'overdue'].includes(t.status);
                  return (
                    <tr data-href={`/visits/${t.visit_id}`}>
                      <td>
                        <strong>{TASK_TYPE_LABELS[t.task_type]}</strong>
                        {t.notes && <div class="muted desc-clip">{t.notes}</div>}
                      </td>
                      <td>
                        <a class="rowlink" href={`/visits/${t.visit_id}`}>{t.plan_number}</a>
                        <div class="muted">{t.vendor_name}</div>
                      </td>
                      {showAll && <td>{t.assigned_to_name}</td>}
                      <td class={overdue(t) ? 'text-red' : ''}>{fmtDate(t.due_date)}</td>
                      <td>{taskBadge(t.status, t.due_date)}</td>
                      <td class="actions">
                        <a class="btn btn--sm btn--icon" href={`/visits/${t.visit_id}`} title="Open visit" aria-label="Open visit"><Icon name="eye" size={15} /></a>
                        {mine && open && t.status !== 'in_progress' && (
                          <IconAction action={`/tasks/${t.id}/start`} icon="play" label="Start task" />
                        )}
                        {mine && open && (
                          <IconAction action={`/tasks/${t.id}/complete`} icon="tick" label="Complete task" class="btn--green" />
                        )}
                        {canReassign(t) && (
                          <IconModalBtn modal={`reassign-${t.id}`} icon="users" label="Reassign task" />
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      {reassignable.map((t) => (
        <Modal id={`reassign-${t.id}`} title={`Reassign: ${TASK_TYPE_LABELS[t.task_type]}`}>
          <form method="post" action={`/tasks/${t.id}/reassign`}>
            <div class="context">{t.plan_number} - {t.vendor_name}, due {fmtDate(t.due_date)}</div>
            <Field label="Assign to">
              <select name="assigned_to_id" required>
                {users.map((u) => (
                  <option value={u.id} selected={u.id === t.assigned_to_id}>{u.full_name} ({ROLE_LABELS[u.role]})</option>
                ))}
              </select>
            </Field>
            <ModalButtons submit="Reassign" />
          </form>
        </Modal>
      ))}
    </>
  ));
});

routes.post('/:id/reassign', async (c) => {
  const user = c.get('user');
  const form = await c.req.formData();
  const assignTo = String(form.get('assigned_to_id') ?? '');
  const task = await first<Task>(c.env.DB, 'SELECT * FROM tasks WHERE id = ?', c.req.param('id'));
  const visit = task ? await first<Visit>(c.env.DB, 'SELECT * FROM visits WHERE id = ?', task.visit_id) : null;
  if (!task || !visit || !['pending', 'in_progress', 'overdue'].includes(task.status) ||
      (!isAdmin(user) && user.id !== visit.vendor_coordinator_id)) {
    flash(c, 'You cannot reassign this task.', 'err');
    return c.redirect('/tasks');
  }
  const target = await first<{ full_name: string }>(c.env.DB, 'SELECT full_name FROM users WHERE id = ? AND is_active = 1', assignTo);
  if (!target) {
    flash(c, 'Pick an active user.', 'err');
    return c.redirect('/tasks');
  }
  await updateRow(c.env.DB, 'tasks', task.id, { assigned_to_id: assignTo }, c.get('realUser').id);
  flash(c, `Task reassigned to ${target.full_name}.`);
  return c.redirect('/tasks');
});

async function transition(c: Context<App, '/:id/start' | '/:id/complete'>, allowed: TaskStatus[], patch: Record<string, unknown>, message: string) {
  const user = c.get('user');
  const task = await first<Task>(c.env.DB, 'SELECT * FROM tasks WHERE id = ?', c.req.param('id'));
  const back = c.req.header('referer')?.includes('/visits/') ? `/visits/${task?.visit_id}` : '/tasks';
  if (!task || (task.assigned_to_id !== user.id && !isAdmin(user))) {
    flash(c, 'You can only update tasks assigned to you.', 'err');
    return c.redirect(back);
  }
  if (!allowed.includes(task.status)) {
    flash(c, 'This task can no longer be updated.', 'err');
    return c.redirect(back);
  }
  await updateRow(c.env.DB, 'tasks', task.id, patch, c.get('realUser').id);
  flash(c, message);
  return c.redirect(back);
}

routes.post('/:id/start', (c) => transition(c, ['pending', 'overdue'], { status: 'in_progress' }, 'Task started.'));
routes.post('/:id/complete', (c) =>
  transition(c, ['pending', 'in_progress', 'overdue'], { status: 'completed', completed_at: now() }, 'Task completed.'));

export default routes;
